# permissions for end users to view dynamicipaddresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamicipaddress-viewer-role
rules:
- apiGroups:
  - pxe.kumple.com
  resources:
  - dynamicipaddresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pxe.kumple.com
  resources:
  - dynamicipaddresses/status
  verbs:
  - get
