# permissions for end users to edit dynamicipaddresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamicipaddress-editor-role
rules:
- apiGroups:
  - pxe.kumple.com
  resources:
  - dynamicipaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pxe.kumple.com
  resources:
  - dynamicipaddresses/status
  verbs:
  - get
