# permissions for end users to edit ipaddresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipaddress-editor-role
rules:
- apiGroups:
  - pxe.kumple.com
  resources:
  - ipaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pxe.kumple.com
  resources:
  - ipaddresses/status
  verbs:
  - get
