
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - pxe.kumple.com
  resources:
  - dynamichostconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pxe.kumple.com
  resources:
  - dynamichostconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - pxe.kumple.com
  resources:
  - dynamichostconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pxe.kumple.com
  resources:
  - ipaddresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pxe.kumple.com
  resources:
  - ipaddresses/finalizers
  verbs:
  - update
- apiGroups:
  - pxe.kumple.com
  resources:
  - ipaddresses/status
  verbs:
  - get
  - patch
  - update
